### ISSUE TITLE
Add a Repository DOI

### ISSUE THREAD

**Issue by Travis-S** [Tomographer/tomographer#2]
To encourage straightfoward citation of the software, having a DOI for the repository could be useful. There is a [GitHub guide](https://guides.github.com/activities/citable-code/) which explains how to do so. The main dependency is to have an account with [Zenodo](https://zenodo.org/).

**Comment by phfaist** [comment]
Good point. I'll have a look at this, thanks.

**Comment by phfaist** [comment]
Done with v2.0.
