### ISSUE TITLE
.mat sample

### ISSUE THREAD

**Issue by echkon** [Tomographer/tomographer#3]
Dear Dr. Philippe Faist,
I am so interested in your project. However, could you give me a sample of .mat file?
Thank you so much.
Another question that I have data without any POVM, how to compute the .mat file?

**Comment by phfaist** [comment]
Hi @echkon, thanks for your interest. You can find a sample .mat file in the repo at `cxx/test/tomorun/test_tomorun_1qubit_analytic_solution.mat`. I realize it might be useful to have a full example in the repo, so I'll try to add one for reference. For your second question, you need to input the POVM elements into the procedure, i.e. they are assumed to be known and any errors in the measurement should be modeled into effective noisy POVM elements (for instance, the POVM operators will no longer be projectors). For an example, see Section 6 of the supplementary materials to https://doi.org/10.1103/PhysRevLett.117.010404 .

**Comment by phfaist** [comment]
You can now check out an example in the repo: https://github.com/Tomographer/tomographer/tree/master/examples/two-qubits-Bell . Let me know if you'd like more info. I'm closing this issue for now, feel free to reopen if this doesn't quite answer your request.

**Comment by echkon** [comment]
Dear Phfaist,
Thank you very much for your answer to me.
This is just because I cannot create thedata.mat from make_data_file.m
I would love to grateful if you could give me that thedata.mat file?
Yours.

**Comment by phfaist** [comment]
there you go (latest commit). -Philippe
